[package]
name = "plx"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.29.0"
ratatui = "0.29.0"
postgres = "0.19.12"

serde = { version = "1.0", features = ["derive"] }
toml = "0.9.8"
dirs = "6.0.0"
shellexpand = "3.1.1"
arboard = "3.6.1"
