[package]
name = "plx"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.29.0"
ratatui = "0.29.0"
rusqlite = { version = "0.37.0", features = ["bundled"] }

serde = { version = "1.0", features = ["derive"] }
toml = "0.9.8"
dirs = "6.0.0"
shellexpand = "3.1.1"
